
target.a-y = \
	libsrc.a

libsrc.a_files-y = \
	list.c \
	queue.c \
	queuea.c \
	stack.c \
	stacka.c \
	selection-sort.c \
	insertion-sort.c \
	shell-sort.c \
	shuffle.c \
	counter-clockwise.c \
	merge-sort.c \
	bottom-up-merge-sort.c \
	quick-sort.c \
	quick-select.c \
	quick-sort-3way.c \
	pqueue.c \
	binary-heap.c \
	heap-sort.c \
	binary-search.c \
	tree.c \
	tree-rb.c

include ../Makefile.lib
